---
language: node_js
node_js:
  - "6"
  - "0.12"

sudo: required
dist: trusty

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta

matrix:
  fast_finish: true

addons:
  apt:
      sources:
        - google-chrome
      packages:
        - google-chrome-stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm config set spin false
  - npm install -g npm@^3
  - npm install -g bower
  - bower --version

install:
  - npm install
  - bower install

script:
  - ember try $EMBER_TRY_SCENARIO try:each
